server:
  port: 8080

spring:
  #dataSource配置
  datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url : jdbc:mysql://47.92.101.196:3306/andon?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC 
        username : root
        password : 123456

  #rabbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: dou
    password: dou123456

#集成mybatis
mybatis:
  type-aliases-package: com.dou.pojo
  mapper-locations: classpath:com/dou/mapper/*.xml
  